//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdCar { get; set; }
        public int IdAccount { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual Account account { get; set; }
        public virtual Car car { get; set; }
    }
}
